### PR TITLE
Functions adapted to the OpenWhisk platform

### PR DESCRIPTION
**Pull request by andersonandrei**
Hello everyone,

Thanks for the benchmark that you provide here.
It has been very useful to me. I have worked with the scheduling of functions on serverless platforms. 
More specifically, I have worked with the OpenWhisk platform in addition to using container images for the dependencies of the functions.

Therefore, I adapted some of the functions available here to be used with OpenWhisk, and I created container images to be attached to their deployments. There is one container image for each function (for almost all of them).

So, with this PR, I'm submitting my modifications with the docker files and the necessary instructions to deploy and use these functions with OpenWhisk.

Thank you,

Best regards,
Anderson Andrei DA SILVA..

### CODE REVIEW

**Comment by kmu-leeky** [comment]
Hello @andersonandrei 

Thank you very much for your work to support OpenWhisk in the FunctionBench. A while ago, we had a request to port FunctionBench to OpenWhisk (#13) and you did a great job. I checked the code and it looks good to be merged. BTW, did you make a publication out of your work with OpenWhisk? If so, please let us know, and I will follow on your work.

Thanks.
Kyungyong.

**Review by hyu-leeky — APPROVED** [review]
Great!

**Comment by andersonandrei** [comment]
Hello @kmu-leeky ,

Thanks for your feedback and for merging the modifications.
Yes, I wrote a paper using FunctioBench as the benchmark, but I'm still waiting for its approval at a conference. As soon as it is published, I will send the details here.

Best regards,
Anderson Andrei DA SILVA.

**Comment by hyu-leeky** [comment]
@andersonandrei good luck for your submission!

**Pull request merged**
